name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'tests/**'
      - 'playwright.config.ts'
      - 'package-lock.json'
      - 'package.json'
  schedule:
    # Run 8 times a day, starting from 09:00 AM Vietnam time (2:00 AM UTC)
    - cron: '0 2 * * *'  # 09:00 AM Vietnam
    - cron: '0 3 * * *'  # 10:00 AM Vietnam
    - cron: '0 4 * * *'  # 11:00 AM Vietnam
    - cron: '0 5 * * *'  # 12:00 PM Vietnam
    - cron: '0 6 * * *'  # 01:00 PM Vietnam
    - cron: '0 7 * * *'  # 02:00 PM Vietnam
    - cron: '0 8 * * *'  # 03:00 PM Vietnam
    - cron: '0 9 * * *'  # 04:00 PM Vietnam
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        working-directory: playwright-tests
        run: npm ci
      - name: Install Playwright Chromium Browser
        working-directory: playwright-tests
        run: npm run install:drivers:chrome
      - name: Run Playwright tests
        working-directory: playwright-tests
        env:
          CI: true
          HEADLESS_MODE: ${{ vars.HEADLESS_MODE }}
          BASE_URL: ${{ secrets.BASE_URL }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          OTP_API_KEY: ${{ secrets.OTP_API_KEY }}
          OTP_API_URL: ${{ secrets.OTP_API_URL }}
        run: npm test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Notify Slack on success
        if: success()
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "channel": "#uncle-k",
              "username": "CI Bot",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<!here> ❌ *Playwright tests failed* on commit ${{ github.sha }}."
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "channel": "#uncle-k",
              "username": "CI Bot",
              "text": "❌ Playwright tests failed on commit ${{ github.sha }}."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
