name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'tests/**'
      - 'playwright.config.ts'
      - 'package-lock.json'
      - 'package.json'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        working-directory: playwright-tests
        run: npm ci
      - name: Install Playwright Chromium Browser
        working-directory: playwright-tests
        run: npm run install:drivers:chrome
      - name: Run Playwright tests
        env:
          CI: true
          HEADLESS_MODE: ${{ vars.HEADLESS_MODE }}
          BASE_URL: ${{ secrets.BASE_URL }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          OTP_API_KEY: ${{ secrets.OTP_API_KEY }}
          OTP_API_URL: ${{ secrets.OTP_API_URL }}
        run: npm run test:chromium
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
